### ISSUE TITLE
Ping failed with error: ping: invalid value

### ISSUE THREAD

**Issue by Xorgos** [Chadsr/NordVPN-NetworkManager#65] opened 2018-01-20 14:21 UTC
Hi again!

Sorry, that I come up with the next problem. After I noticed some instability with Antergos because of "200" package upgrades every day I decided to install Debian 9 to have more stability and consistence in my everyday-setup.

I also installed nordnm v0.3.1 again like described (over pip3) in the installation instructions on this site. But now I have another problem when I'm running nordnm under Debian Stretch.

It seems to be a problem with benchmarking/pinging the server. Everytime I run nordnm I get the following error maybe 100 lines for every ping nordnm does:

"[ERROR] [nordnm.utils]: Ping failed with error: ping: invalid value (`0.2' near `.2') Try 'ping --help' or 'ping --usage' for more information."

After that there are no server in my VPN list and VPN is not activated. "Ping --help" or "ping --usage" doesn't help me and using google also doesn't help me.

Maybe you have a workaround or a hint what goes wrong here.

![bildschirmfoto vom 2018-01-20 15-13-47](https://user-images.githubusercontent.com/35450559/35184403-66be2790-fdf5-11e7-9916-fd5fccf7ad8d.jpg)

Greetings, Xorgos!

**Comment by Chadsr** [comment] 2018-01-21 18:36
I need to get multi-distro unit tests set up ASAP, to prevent update bugs like this...

I modified pinging in v0.3.0, with some timing parameters to speed up benchmarking. Looks like this is unimplmented on Debian's ping version or something. Unfortunately i'm getting some weird bug installing a Debian 9 VM right now, so it's not going to be an instant patch.

Unitl I have some time to fix this and release the patch, I would recommend switching back to v0.2.1 like so:
`pip3 install nordnm==0.2.1`

**Comment by Chadsr** [comment] 2018-01-23 11:08
So, it comes with no suprise that there are multiple implementations of ping and these can vary across distros...

Strangely, I didn't reproduce the above problem on Debian 9, but I did break nordnm's pinging another way. If you check the output of `ping --version` you'll probably see `ping (GNU inetutils)` on the first line.

So thanks to your bug report, I've realised iputils-ping needs to be specified as a dependency on Debian, since inetutils-ping breaks everything.

I will add this dependency to the .deb package of the next patch release (probably today). Now that I have a Debian repository set up for nordnm, I would recommend uninstalling via pip3 and following the new Debian install instructions, so system requirements are handled automatically in the future.

**Comment by Chadsr** [comment] 2018-01-23 11:53
v0.3.2 was just released, so try installing that, via the new Debian installation method and let me know how it goes. Oh, and make sure you uninstall via pip beforehand, in case that causes some conflicts.

Thanks.

**Comment by Chadsr** [comment] 2018-01-24 16:12
v0.3.3 was just released and should solve any ping issues as well as fixing the repository to work with Debian Trusty if you wish to try it out.

Thanks!

**Comment by Chadsr** [comment] 2018-01-30 12:45
@Xorgos did you manage to resolve this issue, or are you still experiencing problems?

**Comment by Chadsr** [comment] 2018-04-25 14:35
I am going to close this issue for now as I am assuming it is resolved. If that is not the case, feel free to re-open it!

**Closed by Chadsr** 2018-04-25 14:35 UTC
Labels: system problem
