### ISSUE TITLE
Program hangs while attempting to benchmark servers on Manjaro

### ISSUE THREAD

**Issue by Drose221193** [Chadsr/NordVPN-NetworkManager#110] opened 2018-09-22 04:14 UTC
While using the command 

sudo nordnm sync -ua us normal udp

the program proceeds to start until it reaches benchmarking servers. At this point it fails to complete the benchmark. I let it sit for about 15 minutes to see if anything would happen and nothing.

Manjaro 17.1.12
Kernel 4.18.9-1
Here is an image for referance
https://ibb.co/bx5NnK

**Comment by Chadsr** [comment] 2018-09-24 12:54
Hi,

This is the first case of complete hanging I have witnessed so far. Usually I see a lot of firewalls causing issues blocking ICMP packets,. If that was the case here, the tool should still show progress and finish with a high error rate.

I will investigate a possible source for hanging, but if you could also check for any router firewall setting blocking ICMP packets that could help narrow it down.

Thanks!

**Comment by Chadsr** [comment] 2018-09-25 13:49
It seems this is related to the maximum number of file descriptors available. As per issue #104, it was brought to my attention that this was a problem, so I have now implemented a hard cap at 512 for the time being (f099ed34b65f29d8cb9ce4e3612f9175cda7ae56).

I will be releasing v0.6.0 shortly containing this amongst other fixes. So try the update when it is available and let me know if the problem is gone for you.

Thanks!

**Comment by Drose221193** [comment] 2018-09-25 23:54
Thanks for the quick reply. Unfortunately when trying to update I receive

ERROR: pkgbase should not be an array

**Comment by Chadsr** [comment] 2018-09-26 19:27
Please try the PKGBUILD again. I just made a modification to fix that. 

Out of interest, what are you using to install from AUR? I hadn't encountered any tool that pedantic before.

**Comment by Drose221193** [comment] 2018-09-27 08:11
I am using Yay

**Comment by Chadsr** [comment] 2018-10-07 14:50
Closing as this seems to be fixed!

**Closed by Chadsr** 2018-10-07 14:50 UTC

**Comment by glubsy** [comment] 2018-10-11 20:39
I've had this problem with 0.5.5 but since 0.6.0 no more problem.

The CPU was churning hard, and the memory usage was sky rocketing (16GB of RAM and it would eat everything). Running Arch Linux, and my ulimit is high:

```
$> ulimit -Hn
1048576
```

Anyway, thanks for fixing the problem, and maintaining the project! :smiley:  :heart:
