### ISSUE TITLE
Can't connect to any server after purging

### ISSUE THREAD

**Issue by Feynman1337** [Chadsr/NordVPN-NetworkManager#48] opened 2017-11-30 12:30 UTC
Hi there,
I wanted to disable the VPN connection so I just type 
`sudo nordnm -p`
but now I cannot connect to any server since it just returns an error message saying
`[ERROR] [nordnm.nordnm:198]: Auto-connect not activated: No active server found matching [gb, normal, tcp].
`
I have tried different servers, reconfigured my credentials, reinstalled nordnm, resynced, updated list of servers.. but so far nothing works.

Thank you for your help!

**Comment by Chadsr** [comment] 2017-11-30 13:36
Hi,

Could you clarify whether there are still VPNs imported to networkmanager after you ran the purge command? The purge command (-p) should remove all existing connections from networkmanager, as well as any auto-connect / kill-switch settings.

You say that you have tried resyncing already. Did that work as intended, giving you a new list of connections imported? If so, can you confirm that [gb, normal, tcp] matched one of the imported connections? Auto-connect will only succeed if there is a connection already imported which matches the parameters you specified.

If you do have a connection matching the auto-connect parameters and it still fails, then something strange and unintended happened and this will need some further investigation..

**Comment by Feynman1337** [comment] 2017-11-30 13:56
Hi Ross,
There are no VPN connections listed in networkmanager, so the purge command has removed them all. If I resync, it says that no new connections are being added, and the list is still empty. 

So I guess that is the problem, that either syncing is not working for me, or it thinks that they are already there and it does not add new ones. If I go into my ~/.nordnm/configs, I can see all the .ovpn configuration files for the servers.

**Comment by Chadsr** [comment] 2017-11-30 15:47
Since you have no VPN connections listed in networkmanager, can you check if `.nordnm/.active_servers` contains any data and if it does, try deleting it.

Secondly, would you mind sharing the contents of your `.nordnm/settings.conf`? Maybe the reason nothing is being synced relates to those settings being too constricting.

**Comment by peteruithoven** [comment] 2017-11-30 16:11
@Feynman1337 could you maybe also include the commands you tried to use to reconnect to a vpn?

**Comment by Feynman1337** [comment] 2017-11-30 18:14
So, there is no .active_servers file:
![1](https://user-images.githubusercontent.com/21260922/33447130-35e14a12-d5fa-11e7-89ce-16d4e77347b0.png)
Here are the settings.conf:
![2](https://user-images.githubusercontent.com/21260922/33447137-3b7668f4-d5fa-11e7-882a-5db5b4e52a0b.png)
And here the command I try (the example one in the readme page)
![3](https://user-images.githubusercontent.com/21260922/33447143-3df043ca-d5fa-11e7-8bd1-9a10a674fb1d.png)

**Comment by Chadsr** [comment] 2017-11-30 19:02
That is peculiar. The fact that I can not replicate this behaviour with the same settings, makes me think this is caused by something specific to your system/network. 

A couple more things:
- What distribution are you using?
- What is the output of `ping 85.159.237.56 -c 5`? (IP is a random NL NordVPN server)

I have a hunch that it may be related to either a missing package, or your network connection has high packet loss and is causing the script to reject all servers. :)

**Comment by peteruithoven** [comment] 2017-11-30 19:43
Isn't one of the issues that the countries blacklist and whitelist are empty? That would explain why it  couldn't find matching servers?

**Comment by Feynman1337** [comment] 2017-11-30 20:46
Hi there,
I am using Argentos. You are right, I am getting all packets lost, and I don't know why. I am using the university wlan (eduroam network), and I get 100% package loss even when pinging google.com, 8.8.8.8, and more. I doubt it is a university problem, because I can ping those addresses in Windows just fine. I tried with another linux laptop and I am getting the same package loss. Any ideas what might cause it? I also tried changing the nameserver in /etc/resolv.conf with Google's DNS but it doesn't solve anything, actually, it makes the connection slower.

Thank you for the help.

**Comment by Chadsr** [comment] 2017-12-01 20:44
@peteruithoven When both lists are empty, all countries are synchronised (they are just empty by default), but I see how that is a bit counter-intuitive :).

@Feynman1337 I can't think of an obvious reason right now. If ICMP was being blocked by a firewall, then a Windows system shouldn't be able to ping, either. If you test the same ping whilst connected to a different network, we can at least narrow it down to either a network or system problem. The fact that it fails on two different Linux systems is puzzling though.

**Comment by Feynman1337** [comment] 2017-12-04 11:57
Well I managed to solve it. I kept trying to connect manually to different servers, and I could connect to uk137, (which is odd, because when I pinged it I got 0% loss, so it should have been detected by syncing). Anyway after connecting to it, I could resync and the server list was no longer empty. So connecting to the VPN avoided the package loss. Which makes me think that it is something related to some firewall the university has, and it somehow lets pings from windows go through and not linux? And maybe when they are encrypted they are not blocked?

**Comment by Chadsr** [comment] 2017-12-04 14:48
That is strange, but i'm glad you managed to find a work-around. 
Nordnm does disable active VPNs when synchronising, so you may encounter the same problem when using sync at your university again. I plan to make this optional in the future (#28).

I would maybe suggest informing whoever manages the university network of this problem, as I can't think of many legitimate reasons that they would need to do this.

For now, I will close this issue as I don't think I'm capable of resolving the network problem further. If you do wish to add something else to this topic in the future, just re-open it. (More information could be useful for others to reference)

Thanks

**Closed by Chadsr** 2017-12-04 14:48 UTC
