### ISSUE TITLE
[ERROR] [nordnm.networkmanager]: Could not find source connection.

### ISSUE THREAD

**Issue by Xorgos** [Chadsr/NordVPN-NetworkManager#62] opened 2018-01-15 10:03 UTC
Hi, 

first of all thank you for your work with NordNM! It worked flawlessly the past time until it got broken a few days ago.

Since a few days I'm not able to connect to my VPN anymore. Everytime I use "sudo nordnm s -uka nl normal tcp" in order to benchmark my servers and autoconnect to a server I receive an errormessage that says:

"[ERROR] [nordnm.networkmanager]: Fehler: Aktivierung der Verbindung ist gescheitert: Could not find source connection." (Translation from German: "Failure: Activation of the connection failed:")

After that there is no connection to my VPN and I'm not able to activate it manually in my connection-overview. I also tried other countries and udp but that also didn't work.

I'm hoping for help ant thank you very much!

Greetings, Xorgos.

**Comment by Chadsr** [comment] 2018-01-15 11:00
Hi,

Thanks for the report, and sorry that something seems to have broken for you. What version are you using when encountering this new error? Do you think it occurred after upgrading nordnm?

Thanks

**Comment by Xorgos** [comment] 2018-01-15 11:05
Thanks for your answer!

It is the newest version - "v0.2.1". No, it worked with this version before then it broke maybe 5 days ago I guess.

I'm using Antergos Linux, maybe incompatibility with other depending packages?

Greeting

**Comment by Chadsr** [comment] 2018-01-15 11:25
Thanks for the information.
I have yet to do testing on Antergos, so there could well be a package issue. I will get back to you when I have found a reason. If you think of any other information that may prove useful in solving this, please let me know.

**Comment by Xorgos** [comment] 2018-01-15 11:29
Thank you! I will let you know!

**Comment by Chadsr** [comment] 2018-01-15 16:09
Could you run `nmcli device status` and tell me what the "STATE" value says for the network interface you use to connect to the Internet?

I have a feeling that the interface is not being managed by NetworkManager and that's causing this issue.

**Comment by Xorgos** [comment] 2018-01-16 04:34
Good Morning!

I ran "nmcli device status" and it says "connected":

DEVICE         TYPE           STATE                   CONNECTION 
enp3s0f0      ethernet     verbunden           enp3s0f0   
lo                   loopback    nicht verwaltet     --         

I installed it manually via AUR keeping it actual with yaourt. 

It's strange - I did nothing on my system exept updating it via yaourt and pacman.

**Comment by Chadsr** [comment] 2018-01-16 09:47
Okay, that all seems fine then. I will have to look into this further, because those were all of my ideas for now.

Could you try deleting all configuration with `sudo nordnm remove --all`? I'm unsure how a problem in the configuration could cause this, but it's worth a try.

**Comment by Xorgos** [comment] 2018-01-17 04:55
Hi!

I deleted and reconfigured my nordnm-configuration and have both packages - openvpn and networkmanager-openvpn - installed. 

Still not working, "Could not find source connection.".

**Comment by Chadsr** [comment] 2018-01-17 08:47
Okay, great.
I'm still thinking that this is a NetworkManager problem and not caused by nordnm, but let's see.

Could you post the output of `journalctl -f -u NetworkManager.service` after running the tool and getting the error? I'm hoping we will find the answer there. (Feel free to remove any personal info)

**Comment by Xorgos** [comment] 2018-01-17 09:34
Here is the result:

-- Logs begin at Sat 2017-12-02 16:30:14 CET. --
Jan 17 10:14:20 antergos NetworkManager[668]: <info>  [1516180460.3090] device (enp3s0f0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
Jan 17 10:14:20 antergos NetworkManager[668]: <info>  [1516180460.3095] device (enp3s0f0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
Jan 17 10:14:20 antergos NetworkManager[668]: <info>  [1516180460.3097] device (enp3s0f0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
Jan 17 10:14:20 antergos NetworkManager[668]: <info>  [1516180460.3098] manager: NetworkManager state is now CONNECTED_LOCAL
Jan 17 10:14:20 antergos NetworkManager[668]: <info>  [1516180460.3167] device (enp3s0f0): Activation: successful, device activated.
Jan 17 10:14:20 antergos NetworkManager[668]: <info>  [1516180460.3180] manager: startup complete
Jan 17 10:14:20 antergos NetworkManager[668]: <info>  [1516180460.3489] bluez5: NAP: added interface **:**:**:**:**:**
Jan 17 10:14:21 antergos NetworkManager[668]: <info>  [1516180461.3746] manager: NetworkManager state is now CONNECTED_GLOBAL
Jan 17 10:15:48 antergos NetworkManager[668]: <info>  [1516180548.7994] audit: op="connection-activate" uuid="12c01f20-7bb0-4d34-91d8-453adff3c74d" name="de223 [normal|p2p] [tcp]" pid=1334 uid=0 result="fail" reason="Could not find source connection."
Jan 17 10:15:48 antergos NetworkManager[668]: <warn>  [1516180548.8072] dispatcher: (3) nordnm_autoconnect_***** failed (failed): Script '/etc/NetworkManager/dispatcher.d/nordnm_autoconnect_*****' exited with error status 4.
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.2286] audit: op="connection-delete" uuid="0c5b7c2e-e4b8-4e17-b28d-94913d61db48" name="de223 [normal|p2p] [udp]" pid=4270 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.3063] audit: op="connection-delete" uuid="12c01f20-7bb0-4d34-91d8-453adff3c74d" name="de223 [normal|p2p] [tcp]" pid=4356 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.4810] audit: op="connection-delete" uuid="52aa0e04-27e1-4095-82b5-169b3469f16b" name="nl138 [normal|p2p] [udp]" pid=4456 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.5270] audit: op="connection-delete" uuid="f59bcca5-a3cf-4f7e-a771-3997c6cbebc3" name="nl138 [normal|p2p] [tcp]" pid=4464 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.6096] audit: op="connection-delete" uuid="e3050529-698d-4f1e-918f-6a5823115b90" name="nl-se1 [double] [tcp]" pid=4480 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.6924] keyfile: add connection /etc/NetworkManager/system-connections/de241 [normal|p2p] [udp] (b834dcf3-9de7-48c0-90a2-d0b2d82cf0d5,"de241 [normal|p2p] [udp]")
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.6931] audit: op="connection-add" uuid="b834dcf3-9de7-48c0-90a2-d0b2d82cf0d5" name="de241 [normal|p2p] [udp]" pid=4489 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.7735] keyfile: add connection /etc/NetworkManager/system-connections/de261 [normal|p2p] [tcp] (19b6946e-8732-4d67-a386-8fe0b1b72704,"de261 [normal|p2p] [tcp]")
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.7741] audit: op="connection-add" uuid="19b6946e-8732-4d67-a386-8fe0b1b72704" name="de261 [normal|p2p] [tcp]" pid=4497 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.8594] keyfile: add connection /etc/NetworkManager/system-connections/de261 [normal|p2p] [udp] (ee006671-59bb-4379-af20-18e2acaadb97,"de261 [normal|p2p] [udp]")
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.8599] audit: op="connection-add" uuid="ee006671-59bb-4379-af20-18e2acaadb97" name="de261 [normal|p2p] [udp]" pid=4505 uid=0 result="success"
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.9810] keyfile: add connection /etc/NetworkManager/system-connections/nl60 [normal|p2p] [udp] (c081dfea-4b90-45e0-a0d6-14addece0898,"nl60 [normal|p2p] [udp]")
Jan 17 10:16:29 antergos NetworkManager[668]: <info>  [1516180589.9814] audit: op="connection-add" uuid="c081dfea-4b90-45e0-a0d6-14addece0898" name="nl60 [normal|p2p] [udp]" pid=4517 uid=0 result="success"
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.0774] keyfile: add connection /etc/NetworkManager/system-connections/nl60 [normal|p2p] [tcp] (21a79b2f-4194-4cb6-88e0-a00a19ebe245,"nl60 [normal|p2p] [tcp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.0778] audit: op="connection-add" uuid="21a79b2f-4194-4cb6-88e0-a00a19ebe245" name="nl60 [normal|p2p] [tcp]" pid=4525 uid=0 result="success"
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.2294] keyfile: add connection /etc/NetworkManager/system-connections/nl1-ru1 [double] [tcp] (eee97bbb-312b-45e8-8cce-08d8bdcd53ed,"nl1-ru1 [double] [tcp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.2298] audit: op="connection-add" uuid="eee97bbb-312b-45e8-8cce-08d8bdcd53ed" name="nl1-ru1 [double] [tcp]" pid=4541 uid=0 result="success"
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.2767] keyfile: update /etc/NetworkManager/system-connections/nl1-ru1 [double] [tcp] (eee97bbb-312b-45e8-8cce-08d8bdcd53ed,"nl1-ru1 [double] [tcp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.2848] keyfile: update /etc/NetworkManager/system-connections/nl60 [normal|p2p] [tcp] (21a79b2f-4194-4cb6-88e0-a00a19ebe245,"nl60 [normal|p2p] [tcp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.2909] keyfile: update /etc/NetworkManager/system-connections/de241 [normal|p2p] [udp] (b834dcf3-9de7-48c0-90a2-d0b2d82cf0d5,"de241 [normal|p2p] [udp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.2964] keyfile: update /etc/NetworkManager/system-connections/de261 [normal|p2p] [tcp] (19b6946e-8732-4d67-a386-8fe0b1b72704,"de261 [normal|p2p] [tcp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.3019] keyfile: update /etc/NetworkManager/system-connections/de261 [normal|p2p] [udp] (ee006671-59bb-4379-af20-18e2acaadb97,"de261 [normal|p2p] [udp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.3074] keyfile: update /etc/NetworkManager/system-connections/nl60 [normal|p2p] [udp] (c081dfea-4b90-45e0-a0d6-14addece0898,"nl60 [normal|p2p] [udp]")
Jan 17 10:16:30 antergos NetworkManager[668]: <info>  [1516180590.3876] audit: op="connection-activate" uuid="19b6946e-8732-4d67-a386-8fe0b1b72704" name="de261 [normal|p2p] [tcp]" pid=4559 uid=0 result="fail" reason="Could not find source connection."

Thanks again for your help!

**Comment by Chadsr** [comment] 2018-01-17 11:55
Hm. I was hoping to find some more verbosity about the problem from NetworkManager, but it seems "Could not find source connection" is all we get.

Two more ideas:
- What's the default route shown by `ip route show` (When the VPN is not connected). If your LAN and the VPN are both trying to use the same subnet, this could be causing issues.
- Does setting `managed=true` as show [here](https://wiki.debian.org/NetworkManager#Enabling_Interface_Management) change anything? By setting it to true, you should be able to force NetworkManager to manage your eth interface, in case it's not doing that properly.

**Comment by Xorgos** [comment] 2018-01-17 12:04
Setting "managed=true" has not changed anything about the problem and "ip route show" shows me the following:

default via 192.168.178.1 dev enp3s0f0 proto dhcp metric 20100 
192.168.178.0/24 dev enp3s0f0 proto kernel scope link src 192.168.178.180 metric 100

**Comment by Chadsr** [comment] 2018-01-17 12:14
Can you try importing a NordVPN server manually to NetworkManager and see if it will work that way?

If it does, then we can safely assume that there is indeed a strange problem related to nordnm which I can not reproduce. If it does not work, then there is definitely a system/networking problem going on here.

**Comment by Chadsr** [comment] 2018-01-18 19:44
Glad to hear you found a (strange) but working fix. If you find it happens again, it's maybe worth submitting an issue to the NetworkManager devs, if they don't already know about it.

I hope the rest of your nordnm usage is a smooth one!

**Comment by mmeinert** [comment] 2018-01-19 16:32
Got the exact same problem on Antergos too, seems related to the killswitch option (-k).
- with : have to select my interface as @Xorgos explained
- without : everything runs actually fine

**Comment by Chadsr** [comment] 2018-01-19 16:52
Thanks for narrowing down the possible source of the problem. There is already some annoying behaviour related to the killswitch option (#47).

I will try and replicate the problem and merge the issues to #47 if they are indeed related.

**Comment by Xorgos** [comment] 2018-01-20 14:24
This problem comes up with every system reboot. So you have to do the workaround everytime or don't use the killswitch. But the killswitch is an important function in my opinion.

**Comment by Chadsr** [comment] 2018-01-23 17:42
I can't quite reproduce this reliably enough to find the root of the problem. I managed to get the behaviour you described, but before I could investigate further, it stopped again.

I think it has some relation to NetworkManager creating default connection profiles when it doesn't find an existing one. So what seems to have stopped the behaviour for me, was removing all wired (in this case) connection profiles and creating a new one.

I will continue investigating a reliable way to make this behaviour happen, but for now I am a little puzzled.

**Comment by Chadsr** [comment] 2018-02-07 12:23
Still trying to narrow down this issue. By any chance, are you reproducing it whilst using XFCE. I'm not that sure why the desktop environment should affect NetworkManager like this, but so far I have only reproduced it on a XFCE instance.

**Comment by mmeinert** [comment] 2018-02-07 13:33
I reinstalled archlinux from scratch and the problem is gone. I think it's related to antergos...

**Comment by Chadsr** [comment] 2018-02-07 14:22
Okay, I think for now I will close this issue and if it ever comes up again, I will carry on looking into it. It seems like a system bug and probably not worth finding a workaround (for now).

Thanks!

**Closed by Chadsr** 2018-02-07 14:22 UTC
Labels: bug, system problem

**Comment by Yanpas** [comment] 2020-03-24 19:08
I'm using classic openvpn, but had the same problem when I was using auto-created enp0s31f6 connection. Creating ethernet profile myself or using wifi helped

**Comment by rene-s** [comment] 2020-04-16 21:14
Ok this is closed but if anyone is researching this: I am still having this issue and I am not even using NordVPN nor do I use OpenVPN. I am using Wireguard from Mullvad.net. 

I am able to connect once I have left-clicked (that's not supposed to do anything actually) the Internet-facing network adapter in NetworkManager settings.
