### ISSUE TITLE
Increasing the number of ping attempts results in servers not being added

### ISSUE THREAD

**Issue by SpaceBison** [Chadsr/NordVPN-NetworkManager#75] opened 2018-02-17 23:15 UTC
I noticed that the bigger value of ping-attempts I set in the config, the less servers are successfully added to NM. I run some tests and there seems to be a relation.

Configuration: all countries, all server types, UDP only

| ping-attempts | number of servers added |
| - | - |
| 1 | 68 |
| 2 | 46 |
| 3 | 25 |
| 4 | 11 |
| 5 | 13 |
| 10 | 1 |
| 15 | 0 |

**Comment by Chadsr** [comment] 2018-02-18 11:19
Thanks for the interesting observation. I had definitely not noticed this before.

I will look into it ASAP, to determine if it's purely a bug, or related to specific network configurations.

**Comment by SpaceBison** [comment] 2018-03-29 17:09
As of version 0.4.0, the problem seems to still persist. This is the output I get with 5 pings:
```
[INFO] [nordnm.nordnm]: Checking for new connections to import...
[INFO] [nordnm.nordnm]: Benchmarking 326 servers...
[INFO] [nordnm.nordnm]: Benchmarked 191 servers successfully (58.59%). Took 5.73 seconds.
[WARNING] [nordnm.nordnm]: A large quantity of tests failed. You might want to check the reliability of your network.
[INFO] [nordnm.nordnm]: Removing all active connections...
```
and with 1 ping:
```
[INFO] [nordnm.nordnm]: Checking for new connections to import...
[INFO] [nordnm.nordnm]: Benchmarking 326 servers...
[INFO] [nordnm.nordnm]: Benchmarked 310 servers successfully (95.09%). Took 4.70 seconds.
[INFO] [nordnm.nordnm]: Removing all active connections...
```

**Comment by BobbyBabes** [comment] 2018-04-03 15:08
Experiencing similar.
Pastebin of last two attempts with full copy of screen : [https://pastebin.com/C925SmpC](https://pastebin.com/C925SmpC)

I don't mind the low number of connections though. But alas, the specific server that I tested with and reached excellent speeds with (91 Mbps down and 29 Mbps up) is never added to NetworkManager. And only randomly when changing the auto-connect setting from the command line with `sudo nordnm -uka nl normal udp`. The other nl servers are all at least 15 Mbps slower down and 5 Mbps up. Still good though.

On both attempts : first removed everything, then reinitialised with all servers.
First attempt with 10 pings. Second attempt with the default, 5 pings. Weird thing is that less connections were added with the lower ping count.

First with 10 pings :
```
[INFO] [nordnm.nordnm]: Benchmarking 3437 servers...
[INFO] [nordnm.nordnm]: Benchmarked 3373 servers successfully (98.14%). Took 31.56 seconds.
[INFO] [nordnm.nordnm]: No active connections to remove.
[INFO] [nordnm.nordnm]: Adding new connections...
[INFO] [nordnm.nordnm]: 163 new connections added.
```
Second with 5 pings :
```
[INFO] [nordnm.nordnm]: Benchmarking 3436 servers...
[INFO] [nordnm.nordnm]: Benchmarked 3363 servers successfully (97.88%). Took 29.74 seconds.
[INFO] [nordnm.nordnm]: No active connections to remove.
[INFO] [nordnm.nordnm]: Adding new connections...
[INFO] [nordnm.nordnm]: 155 new connections added.
```

**Comment by Chadsr** [comment] 2018-04-05 11:42
I just ran some tests of my own and got some very different results:

| ping-attempts | benchmarking success |
| - | - |
| 1 | Benchmarked 2047 servers successfully (98.60%). Took 14.82 seconds. |
| 2 | Benchmarked 2050 servers successfully (98.80%). Took 15.01 seconds. |
| 3 | Benchmarked 2051 servers successfully (98.84%). Took 17.32 seconds. |
| 4 | Benchmarked 2050 servers successfully (98.80%). Took 16.08 seconds. |
| 5 | Benchmarked 2051 servers successfully (98.84%). Took 17.31 seconds. |
| 10 | Benchmarked 2052 servers successfully (98.89%). Took 19.62 seconds. |
| 15 | Benchmarked 2052 servers successfully (98.89%). Took 23.07 seconds. |

So from these results, I actually witness a slight increase in benchmarking success, when more ping attempts are made (which is what I would expect).

The success of pinging during benchmarking heavily relies on the network allowing large quantities of ping (ICMP) packets to be sent in parallel and rapid succession. What I think we are witnessing in your case (@SpaceBison ) is your router (or other hardware with network security settings) enforcing ICMP flood protection, preventing ping responses being received, causing failed benchmarks. This would also explain the pattern we see with more ping attempts causing more benchmarks to fail.

I see issues caused by ICMP flood protection a lot, so it is a big concern of mine. Resolutions I can think of include:
1. Users disabling/limiting their ICMP flood protection. (Not ideal, or even possible in some cases)
2. Providing settings to fine-tune the speed at which benchmarking is done. (e.g. Adding a "slow-mode" to bypass ICMP flooding enforcement. This could make nordnm VERY slow but more reliable.)
3. Tweak nordnm to benchmark a smaller quantity of servers. (e.g. Only benchmark the top 10 lowest load servers instead of considering all)
4. Switching from ping as a measure of network latency, to something more naive but less problematic such as geographical distance to the VPN server. (I don't think this would provide a reliable measure)

To me, the most viable solution is point 3, possibly combined with point 2. Nordnm currently takes a brute force approach to benchmarking and attempts to ping all options with less than 90% load/usage. Modifying the approach so only, say the top 10 lowest loaded servers are considered would likely solve this problem with little negative impact.

Well this response turned into a bit of an essay, so I will stop here and mention that some discussion of ways to resolve this would be beneficial. There may be some options which I have overlooked, or there may be negative consequences of points such as no. 3 which I have not yet realised.

**Comment by BobbyBabes** [comment] 2018-04-05 12:14
Correct. But benchmarking success is not what I posted about. That is going very well from what I can determine. But it's the addition of far fewer connections that is weird.
Looking ast the 2 samples I posted earlier:
3373 servers benchmarked successfully. But only 163 connections were added to the NetworkManager widget.
3363 servers benchmarked successfully. But only 155 connections were added to the NetworkManager widget.

This was just for testing, with a all servers. I would normally choose to bench nl, us, ca, gb, de, be, sg. But then I'm left with 10 to 20 connections added. Although many more would qualify because of the inclusion of the us. And all the us connections that are added are in CA or AZ. Which can never be optimal because I'm based in Europe mainland. And for example I've never seen server connections to NY state or FL been added to NetworkManager. And never to Canada.

**Comment by bocekm** [comment] 2018-04-24 08:44
Thanks to this issue, I've managed to get 68 active servers out of 3864 benchmarked with ping-attempts = 1. I was getting 4 active servers or less with ping-attempts = 5.
Anyway, I'm still looking for a better solution.
I've disabled both router and computer firewalls, so it seems like my ISP blocking the ICMP requests.

**Comment by Chadsr** [comment] 2018-05-09 11:49
Since the main issue here seems to be related to failed ping attempts, I would like to close this and merge the discussion into issue #83. If you feel there is something more relevant to this issue, please do feel free to re-open it!

**Closed by Chadsr** 2018-05-09 11:49 UTC
