### ISSUE TITLE
Very few connections added

### ISSUE THREAD

**Issue by florensie** [Chadsr/NordVPN-NetworkManager#84] opened 2018-04-15 16:15 UTC
For some reason NordNM doesn't add many connections. I'm assuming it adds the lowest-latency server in each category and country selected. I only get 4-10 connections added while I have all these settings: countries `BE NL UK FR`, `Dedicated IP`, `Double VPN`, `Onion`, `P2P` and `Standard`, both `TCP` and `UDP`. Sometimes it can't even find an autoconnect server.

An example of connections added for those settings:
![image](https://user-images.githubusercontent.com/13403842/38780576-2d2145a4-40d9-11e8-88fc-79b45e5ba579.png)
I have never gotten anything other than `normal` or `normal | P2P` and I don't think I have ever gotten a UK server.

https://pastebin.com/swqyrMiB

**Comment by florensie** [comment] 2018-04-15 16:25
Also how is a server both for p2p and normal at the same time? Is there anything you need to do to choose between both or is it automatically both at the same time.

**Comment by Chadsr** [comment] 2018-04-16 10:25
Hi and thanks for your feedback.

That's very unusual that the other categories do not get synchronised. I haven't witnessed that behavior yet and will attempt to reproduce it to find a possible reason.

Regarding UK servers not being synchronised with your current settings - This is caused by an annoying inconsistency with the NordVPN API, where United Kingdom servers are listed by the country code 'GB', but in their domain names they are referred to as 'UK'. So unintuitively right now, we need use 'GB' to import UK servers. I was hoping to avoid adding a hacky rename to address this, but I will re-asses the problem again. For a comprehensive list of available country codes, you can use the command `sudo nordnm list --countries`.

In reply to your second comment, NordVPN often has crossover between the two categories, so one `[normal|p2p]` connection caters for both a standard connection and a P2P friendly connection without any further input.

Anyway, I will get back to you as soon as possible in regards to the issue of some categories not being synchronised.

**Comment by Chadsr** [comment] 2018-04-16 15:34
PR #85 fixes the missing Onion VPN connections - caused by a tiny change in the NordVPN API.

With your exact settings I do actually get dedicated and double servers synchronising as expected. 
What I think may have happened in your case, is that all server options yielded a score of zero, which currently tells nordnm to completely exclude them. If you try synchronising again and do get dedicated and double servers imported to Network Manager, we will be able to confirm my assumption.
To fix this case (which I think is causing your problem), I have pushed 71c8368f6958dc597ab518c52986a3e7abc9847a, which allows the consideration of zero scoring servers and also increases the load % threshold to exclude a server from 90 to 95.

Both of these fixes will be in the next release, which I hope to have out in the next few days once another important fix or two is completed.

**Comment by florensie** [comment] 2018-04-16 15:34
Thanks for your fast and reply. If there are any other details/logs I can provide you with I'd be happy to do so.

**Comment by florensie** [comment] 2018-04-16 15:42
Haha, you replied right before I did. I'll have a look at resyncing my connections.

**Comment by florensie** [comment] 2018-04-16 15:56
Actually now I'm it isn't finding any new connections anymore.

https://pastebin.com/eJiJ6SsE
In this pastebin you can see me first trying to sync my original config again and then with an updated config. I even tried re-entering my credentials. Not sure if this could be related but yesterday I was still on my 3-day trial and today I activated my 7-day trial from the android app.

**Comment by bocekm** [comment] 2018-04-24 08:05
I'm not getting any active servers.
```
[shell@09:58:38 ~]
$ sudo nordnm sync
     _   _               _ _   _ ___  ___
    | \ | |             | | \ | ||  \/  |
    |  \| | ___  _ __ __| |  \| || .  . |
    | . ` |/ _ \| '__/ _` | . ` || |\/| |
    | |\  | (_) | | | (_| | |\  || |  | |
    \_| \_/\___/|_|  \__,_\_| \_/\_|  |_/   v0.4.0 (Latest)

[INFO] [nordnm.nordnm]: Checking for new connections to import...
[WARNING] [nordnm.nordnm]: Active VPN(s) disabled for accurate benchmarking. Your connection is not secure until these are re-enabled.
[INFO] [nordnm.nordnm]: Benchmarking 3868 servers...
[INFO] [nordnm.nordnm]: Benchmarked 2090 servers successfully (54.03%). Took 27.71 seconds.
[WARNING] [nordnm.nordnm]: A large quantity of tests failed. You might want to check the reliability of your network.
[INFO] [nordnm.nordnm]: Removing all active connections...
[INFO] [nordnm.networkmanager]: Auto-connect disabled.
[INFO] [nordnm.nordnm]: Adding new connections...
[INFO] [nordnm.nordnm]: No new connections added.
[INFO] [nordnm.networkmanager]: DNS leak protection enabled.
[shell@10:01:41 ~]
$ sudo nordnm l --active-servers
     _   _               _ _   _ ___  ___
    | \ | |             | | \ | ||  \/  |
    |  \| | ___  _ __ __| |  \| || .  . |
    | . ` |/ _ \| '__/ _` | . ` || |\/| |
    | |\  | (_) | | | (_| | |\  || |  | |
    \_| \_/\___/|_|  \__,_\_| \_/\_|  |_/   v0.4.0 (Latest)

[WARNING] [nordnm.nordnm]: No active servers to display.
```

**Comment by Chadsr** [comment] 2018-04-27 19:16
The bug fix preventing Onion routed servers from being synchronised has made its way into v0.5.0, which was just released. Another fix was also released which should prevent zero servers from being synchronised, but I will need some feedback to confirm that.

Regarding the irregular quantity of synced servers, I would like to merge the discussion into issue #83, where some other users and I have already been discussing possible solutions - One of which (slow-mode) has just been released as well.

Feel free to give some feedback regarding the first issues mentioned in this discussion, and for the latter head over to #83 to keep up to date and/or contribute to a fix. :)

Thanks!

**Comment by Chadsr** [comment] 2018-05-08 09:49
Since the onion server problem is now solved and I want to try and merge any other related discussion as mentioned above, I will close this issue for now. If you feel like there is something to add here still, do not hesitate to re-open it.

Thanks!

**Closed by Chadsr** 2018-05-08 09:49 UTC
