### ISSUE TITLE
Set Up on UBUNTU 18 LTS

### ISSUE THREAD

**Issue by PierreLeGit** [Chadsr/NordVPN-NetworkManager#103] opened 2018-08-06 14:56 UTC
I all,

Unable to install this tool. 3 poor commands result a big fail lol.
1: 
-> wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
<- OK
2:
-> sudo apt-add-repository "https://dl.bintray.com/chadsr/nordnm-deb main"
<- Hash error all time : 1329 != 1253
3:
->sudo apt update && sudo apt install nordnm
<- Hash error all time : 1329 != 1253 ... Again

Can you fix-it?

**Comment by PierreLeGit** [comment] 2018-08-06 14:59
This is on the original Ubuntu 18.04 LTS 64bit. Without any additional packages installed.
Thanks a lot.

**Comment by Chadsr** [comment] 2018-08-06 17:53
Thanks for the report. I can confirm that something is wrong with the bionic (18.04) package, but I have yet to determine why this appears to be corrupted.

A fix for now, would be to edit your `/etc/apt/sources.list` and change the line `deb https://dl.bintray.com/chadsr/nordnm-deb bionic main` to `deb https://dl.bintray.com/chadsr/nordnm-deb xenial main` and then run `sudo apt update && sudo apt install nordnm`. This is simply switching to the Xenial (16.04) repo which is working fine.

I will update this issue when the Bionic repo is functional again.

**Comment by PierreLeGit** [comment] 2018-08-14 16:32
Thanks for reply,
For the basic user (I've recently switched M$ to Ubuntu), it's hard to setup this tool:

Allright for the source.list:
deb https://dl.bintray.com/chadsr/nordnm-deb xenial main
# deb-src https://dl.bintray.com/chadsr/nordnm-deb xenial main

let's go to install:
>wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
<OK

>sudo apt update && sudo apt install nordnm
<Ign:1 https://dl.bintray.com/chadsr/nordnm-deb xenial InRelease
Réception de:2 https://dl.bintray.com/chadsr/nordnm-deb xenial Release [1 840 B]
Ign:4 http://ppa.launchpad.net/pmcenery/ppa/ubuntu bionic InRelease            
Atteint:5 http://security.ubuntu.com/ubuntu bionic-security InRelease          
Atteint:6 http://fr.archive.ubuntu.com/ubuntu bionic InRelease                 
**Err:7 http://ppa.launchpad.net/pmcenery/ppa/ubuntu bionic Release              
  404  Not Found [IP : 91.189.95.83 80]**
Atteint:8 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease         
Atteint:9 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease
Lecture des listes de paquets... Fait                                          
**E: Le dépôt http://ppa.launchpad.net/pmcenery/ppa/ubuntu bionic Release n'a pas de fichier Release.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut
N: Voir les pages de manuel d'apt-secure(8) pour la création des dépôts et les détails de configuration d'un utilisateur.**

Sorry for the no US terminal ;) However, I can find a 404 not found and below:
E: No Release File.
N: Update from repository cannot start safely and is disable by default

Can you help about that?
Thanks a lot.

**Comment by Chadsr** [comment] 2018-09-09 12:17
Sorry for the big delays in responding.

It has been a while since I used aptitude (apt) based package manager, but it seems that there is a problem with another of your sources; `http://ppa.launchpad.net/pmcenery/ppa/ubuntu bionic Release`. If you try disabling/removing this, I think your `apt update` will function properly again.

**Comment by peteruithoven** [comment] 2018-09-11 09:48
I think I'm experiencing the same issue on the latest Elementary OS Juno (beta), which is based on Ubuntu 18.04.

```
$ sudo apt-add-repository "https://dl.bintray.com/chadsr/nordnm-deb main"
Hit:1 http://nl.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease                                           
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]                                           
Get:4 http://nl.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]                                          
Get:5 http://packages.elementary.io/appcenter bionic InRelease [5894 B]                                               
Hit:6 http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic InRelease                                          
Hit:7 http://ppa.launchpad.net/openscad/releases/ubuntu bionic InRelease                                              
Hit:8 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease                                       
Ign:9 https://dl.bintray.com/chadsr/nordnm-deb bionic InRelease                                                       
Get:10 http://nl.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]
Get:11 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [48,0 kB]
Get:12 https://dl.bintray.com/chadsr/nordnm-deb bionic Release [1840 B]                      
Get:13 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [131 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [166 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [62,6 kB]                    
Get:16 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [319 kB]                             
Get:17 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [283 kB]                            
Get:18 https://dl.bintray.com/chadsr/nordnm-deb bionic Release.gpg [821 B]     
Get:19 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [120 kB]                        
Get:20 https://dl.bintray.com/chadsr/nordnm-deb bionic/main i386 Packages [1253 B]    
Err:20 https://dl.bintray.com/chadsr/nordnm-deb bionic/main i386 Packages                     
  File has unexpected size (1329 != 1253). Mirror sync in progress? [IP: 159.122.18.156 443]
  Hashes of expected file:
   - Filesize:1253 [weak]
   - SHA256:404ddc83bfb6270a33f1201f24cc719aca4ec680639a17246568aa7aa776a729
   - SHA1:ce37c82f5cfe79f60573150adee9d32aa3555385 [weak]
   - MD5Sum:f4000ab9ecbb0d73e21a9c37209aef92 [weak]
  Release file created at: Mon, 23 Jul 2018 14:45:25 +0000
Get:21 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [138 kB]                         
Get:22 https://dl.bintray.com/chadsr/nordnm-deb bionic/main amd64 Packages [1253 B]                                   
Err:22 https://dl.bintray.com/chadsr/nordnm-deb bionic/main amd64 Packages
  
Get:23 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48 Icons [31,4 kB]
Get:24 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64 Icons [53,7 kB]
Get:25 http://nl.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 128x128 Icons [128 kB]
Get:26 http://nl.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [180 kB]
Get:27 http://nl.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [180 kB]
Get:28 http://nl.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [159 kB]
Get:29 http://nl.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 48x48 Icons [165 kB]
Get:30 http://nl.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 64x64 Icons [271 kB]
Get:31 http://nl.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 128x128 Icons [686 kB]
Get:32 http://nl.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2468 B]
Get:33 http://nl.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [5100 B]
Fetched 3386 kB in 5s (718 kB/s)                                         
Reading package lists... Done
E: Failed to fetch https://dl.bintray.com/chadsr/nordnm-deb/dists/bionic/main/binary-i386/Packages.bz2  File has unexpected size (1329 != 1253). Mirror sync in progress? [IP: 159.122.18.156 443]
   Hashes of expected file:
    - Filesize:1253 [weak]
    - SHA256:404ddc83bfb6270a33f1201f24cc719aca4ec680639a17246568aa7aa776a729
    - SHA1:ce37c82f5cfe79f60573150adee9d32aa3555385 [weak]
    - MD5Sum:f4000ab9ecbb0d73e21a9c37209aef92 [weak]
   Release file created at: Mon, 23 Jul 2018 14:45:25 +0000
E: Failed to fetch https://dl.bintray.com/chadsr/nordnm-deb/dists/bionic/main/binary-amd64/Packages.bz2  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

When I visit https://dl.bintray.com/chadsr/nordnm-deb/dists/bionic/main/binary-amd64/Packages.bz2 in a browser is does download a file. 

Please let me know if I can help you debug this issue.

**Comment by Chadsr** [comment] 2018-09-11 14:19
As far as I can tell, the bionic package is corrupted somehow. Which is very strange as the whole process is automated. I'm hoping that rolling an update soon will simply make it work again. If that is not the case, then I will have some more digging to do.

For now, as explained in my first comment on this issue, you can switch to the xenial package source without any issues!

**Comment by peteruithoven** [comment] 2018-10-17 12:46
Tried this again and now it seems to work perfectly!

**Comment by Chadsr** [comment] 2019-04-22 19:54
Closing as I believe this issue is long gone now.

**Closed by Chadsr** 2019-04-22 19:54 UTC
Labels: bug, packaging issue
